# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"
languageCode = "en-us"
publishDir = "docs"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
